modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="juicyraspberrypie"
version="${file.jarVersion}"
displayName="JuicyRaspberryPie Mod"
displayURL="http://wensheng.org/juicy"
authors="Wensheng Wang"
description='''
Later.
'''
[[dependencies.juicyraspberrypie]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.juicyraspberrypie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
