name: Build and Deploy

on:
  # タグプッシュによる自動トリガー（例: v1.21.4-0.6.14）
  push:
    tags:
      - 'v*'
  # GitHub Actions の手動トリガー
  workflow_dispatch:
    inputs:
      deploy_targets:
        description: 'Deployment targets (comma-separated, e.g. staging,production)'
        required: true
        default: 'staging'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Extract versions from Gradle
        id: gradle_versions
        run: |
          MC_VERSION=$(./gradlew -q printMcVersion)
          PLUGIN_VERSION=$(./gradlew -q printPluginVersion)
          FULL_VERSION="${MC_VERSION}-${PLUGIN_VERSION}"
          echo "MC_VERSION=${MC_VERSION}" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=${PLUGIN_VERSION}" >> $GITHUB_ENV
          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV

      - name: Build plugin
        run: ./gradlew build

      # workflow_dispatch での手動トリガーの場合、入力値を使用
      - name: Set deploy targets for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "TARGETS=${{ github.event.inputs.deploy_targets }}" >> $GITHUB_ENV

      # タグプッシュの場合は、デフォルトで staging にデプロイ
      - name: Set deploy targets for tag push
        if: github.event_name == 'push'
        run: echo "TARGETS=staging" >> $GITHUB_ENV

      # stagingへのデプロイ
      - name: Deploy to staging
        if: contains(env.TARGETS, 'staging')
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PATH: ${{ secrets.FTP_PATH }}
        run: |
          JAR_PATH="build/libs/mc-remote-${MC_VERSION}-${PLUGIN_VERSION}.jar"
          lftp -c "
            open ftp://${FTP_USER}:${FTP_PASS}@${FTP_HOST};
            cd ${FTP_PATH};
            if [ -d McRemote ]; then rm -r McRemote; fi;
            glob -a rm mc-remote*.jar;
            put ${JAR_PATH};
            bye
          "
          echo "Deployed to staging environment"

      # タグプッシュ（自動リリースの場合）のときのみリリース作成
      - name: Create GitHub Release
        if: github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Automatically generated release for version ${{ github.ref_name }}."
          draft: false
          prerelease: false